import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api, explainIncident } from "../api";
import type { IncidentExplanation } from "../api";
import { useFetch } from "../hooks";
import {
  Empty,
  ErrorBox,
  JsonView,
  KeyValueTable,
  Loading,
  ModeBadge,
  fmtTs,
} from "../ui";

export default function RunTrace({ keyVersion }: { keyVersion: number }) {
  const { id } = useParams<{ id: string }>();
  const run = useFetch(() => api.evalRun(id ?? ""), [keyVersion, id]);
  const timeline = useFetch(() => api.traceTimeline(id ?? ""), [keyVersion, id]);

  const loading = run.loading || timeline.loading;
  const err = run.error ?? timeline.error;

  const [candidate, setCandidate] = useState("candidate-flawed");
  const [baseline, setBaseline] = useState("baseline");
  const [explaining, setExplaining] = useState(false);
  const [explainError, setExplainError] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<IncidentExplanation | null>(null);

  async function runExplain() {
    if (!id) return;
    setExplaining(true);
    setExplainError(null);
    setExplanation(null);
    try {
      const ex = await explainIncident(id, candidate, baseline, run.data?.mode ?? "fixture");
      setExplanation(ex);
    } catch (e) {
      setExplainError(e instanceof Error ? e.message : String(e));
    } finally {
      setExplaining(false);
    }
  }

  return (
    <div>
      <div className="page-head">
        <p>
          <Link to="/failures">← Failure details</Link>
        </p>
        <h1>Trace timeline</h1>
        <p className="mono muted">eval run {id}</p>
      </div>

      {loading && <Loading label="Loading trace…" />}
      {err && (
        <ErrorBox
          message={err}
          onRetry={() => {
            run.reload();
            timeline.reload();
          }}
        />
      )}

      {!loading && !err && run.data && (
        <div className="card">
          <h3>Eval run</h3>
          <KeyValueTable
            obj={{
              id: run.data.id,
              scenario_id: run.data.scenarioId,
              trial_index: run.data.trialIndex,
              status: run.data.status,
              error: run.data.error,
            }}
          />
          <p>
            <ModeBadge mode={run.data.mode} />
          </p>
          <JsonView value={run.data.metrics} summary="view metrics" />
        </div>
      )}

      {!loading && !err && timeline.data && (
        <div className="card">
          <h3>Events (chronological)</h3>
          {timeline.data.length === 0 ? (
            <Empty message="No trace events recorded for this run yet." />
          ) : (
            <ol className="timeline">
              {timeline.data.map((ev) => (
                <li key={ev.id}>
                  <div className="event-head">
                    <span className="kind">{ev.kind}</span>
                    <span className="event-name">{ev.name}</span>
                    <span className="event-ts">{fmtTs(ev.ts)}</span>
                    {ev.sanitized && <span className="badge badge-neutral">sanitized</span>}
                  </div>
                  <div className="mono muted">
                    trace {ev.traceId.slice(0, 8)} · span {ev.spanId.slice(0, 8)}
                  </div>
                  <JsonView value={ev.payload} summary="event payload" />
                </li>
              ))}
            </ol>
          )}
        </div>
      )}

      <div className="card">
        <h3>Incident explanation</h3>
        <p className="muted">
          Evidence-based analysis: observed facts come from the trace above;
          hypotheses are labeled and never asserted as causes.
        </p>
        <div className="form-grid">
          <div className="form-field">
            <label htmlFor="ex-candidate">Candidate version</label>
            <input id="ex-candidate" value={candidate} onChange={(e) => setCandidate(e.target.value)} />
          </div>
          <div className="form-field">
            <label htmlFor="ex-baseline">Baseline version</label>
            <input id="ex-baseline" value={baseline} onChange={(e) => setBaseline(e.target.value)} />
          </div>
        </div>
        <p>
          <button className="btn" disabled={explaining} onClick={runExplain}>
            {explaining ? "Analyzing…" : "Explain this failure"}
          </button>
        </p>
        {explainError && <ErrorBox message={explainError} onRetry={runExplain} />}
        {explanation && (
          <div>
            <p className="muted mono">
              generated by {explanation.generated_by} · mode {explanation.mode}
            </p>
            <h4>Configuration changes</h4>
            <ul>
              {explanation.configuration_changes.map((c, i) => (
                <li key={i} className="mono">{c}</li>
              ))}
            </ul>
            <h4>Hypotheses (not proven)</h4>
            <ul>
              {explanation.hypotheses.map((h, i) => (
                <li key={i}>{h}</li>
              ))}
            </ul>
            <h4>Suggested controlled experiments</h4>
            <ul>
              {explanation.suggested_experiments.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ul>
            <p className="muted"><em>{explanation.causal_certainty}</em></p>
            <JsonView value={explanation.observed_facts} summary="observed facts (trace-derived)" />
          </div>
        )}
      </div>
    </div>
  );
}
