import { Link } from "react-router-dom";
import { api } from "../api";
import { useFetch } from "../hooks";
import { DemoNote, Empty, ErrorBox, Loading } from "../ui";

export default function Versions({ keyVersion }: { keyVersion: number }) {
  const { data, loading, error, reload } = useFetch(() => api.versions(), [keyVersion]);

  return (
    <div>
      <div className="page-head">
        <h1>Agent versions</h1>
        <p>Registered agent configurations with stable fingerprints.</p>
      </div>
      <DemoNote text="Seeded demo data — synthetic. Version registry entries are generated by the demo seed script." />

      {loading && <Loading label="Loading agent versions…" />}
      {error && <ErrorBox message={error} onRetry={reload} />}
      {!loading && !error && data && (
        data.length === 0 ? (
          <Empty message="No agent versions yet." />
        ) : (
          <div className="table-scroll">
            <table className="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Model</th>
                  <th>Fingerprint</th>
                  <th>Doc snapshot</th>
                  <th>Policy version</th>
                </tr>
              </thead>
              <tbody>
                {data.map((v) => (
                  <tr key={v.id}>
                    <td>
                      <Link to={`/versions/${v.id}`}>{v.name}</Link>
                    </td>
                    <td className="mono">{v.modelId}</td>
                    <td className="mono">{v.fingerprint.slice(0, 16)}…</td>
                    <td className="mono">{v.docSnapshotId.slice(0, 8)}</td>
                    <td>{v.policyVersion}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )
      )}
    </div>
  );
}
